---

- hosts: hosts
  become: true

  tasks:
    - name: Install apache2
      apt: name=apache2 state=absent
      when: ansible_os_family == "Debian"

    - name: Install httpd
      yum: name=httpd state=latest
      when: ansible_os_family == "RedHat"