--- 

- hosts: ubuntu
  
  vars:
    - var1: cool stuff here
    - var2: cool stuff there
  
  tasks: 
    - name: echo stuff
      shell:  echo "{{var1}} is var, but var2 is {{var2}}" > /home/nsindiso/Desktop/{{ansible_os_family}}.txt