--- 

- hosts: hosts
  become: yes
  tasks:
    - name: do a uname
      shell: uname -a > /home/nsindiso/Desktop/results.txt

    - name: whoami
      shell: whoami >> /home/nsindiso/Desktop/results.txt