---

- hosts: ubuntu
  become: yes

  tasks:
    - name: install stuff
      apt: name={{item}} update_cache=yes state=latest
      with_items:
        - vim
        - nano
        - apache2

    - name: show file contents
      debug: msg={{ item }}
      with_file:
        - file1.txt
        - file2.txt

    - name: show sequence
      debug: msg={{  item  }}
      with_sequence: start=1 end=10