---

- name: Gather IOS Facts
  hosts: ios
  connection: local

  tasks:
    - name: Gather IOS facts
      ios_facts:
        gather_subset: all

    - name: What is the ios version?
      debug:
        var: ansible_net_version 

    - name: What is the ios hostname? 
      debug:
        var: ansible_net_hostname


