---

- name: Create Template
  hosts: ios_xe
  connection: local

  tasks:
    - name: Create Template
      with_items: "{{ local_loopback }}"
      template: src="files/ietf_interface.j2" dest="./output.json"

    - name: Create Loopbacks with RESTCONF
      with_items: "{{local_loopback}}"
      restconf_config:
        method: post
        format: json
        path: /data/ietf-interfaces:interfaces
        content: "{{new_loop | to_json}}"
        #content: "{{lookup('file' , './output.json') | string }}"
      register: results
      ignore_errors: true

    - name: print output
      debug: msg= ''{{ results }}''

    - name: Delete Interface
      with_items: "{{local_loopback}}"
      restconf_config:
        method: delete
        format: json
        path: /data/ietf-interfaces:interfaces/interface={{item.name}}
