ansible_connection: network_cli
ansible_network_os: ios
ansible_user: nsindiso
ansible_password: bulawayo
ansible_become: yes
ansible_become_method: enable
ansible_become_password: bulawayo
ansible_ssh_common_args: '-o ProxyCommand="ssh -W %h:%p -q bastion01"'