---

ansible_connection: "httpapi"
ansible_network_os: "restconf"
ansible_httpapi_use_ssl: true
ansible_httpapi_port: 443
ansible_httpapi_validate_certs: false
ansible_httpapi_restconf_root: "/restconf"
ansible_user: "nsindiso"
ansible_password: "bulawayo"

local_loopback:
  - name: "Loopback200"
    desc: "Created by Ansible"
    ip_address: 10.99.99.1
    prefix: 255.255.255.0

new_loop:
  ietf-interfaces:interface:
    - name: "Loopback100"
      type: "iana-if-type:softwareloopback"
      enabled: true
      ietf-ip: ipv4
      address:
        - ip: 10.99.99.1
          netmask: 255.255.255.0